# Each route describes how an incoming URL is going to be processed by Platform.sh.
"https://uat.stalk.exchange/":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: false

"https://uat2.stalk.exchange/":
    type: upstream
    upstream: "app2:http"
    cache:
        enabled: false