# Each route describes how an incoming URL is going to be processed by Platform.sh.
"https://www.{default}/":
    type: upstream
    upstream: "app:http"

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"

"https://bbc.new-branch-5uumuga-gwsfl4vu7bocy.eu-3.platformsh.site/":
    type: redirect
    to: "https://www.blueberrycloud.ca/"